name: Tests
on:
  pull_request:
    branches:
      - "**"
    types:
      - "opened"
      - "synchronize"
concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number }}
  cancel-in-progress: true
jobs:
  test:
    name: Run Jest tests
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v4
      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: yarn
      - name: Install dependencies
        run: yarn
      - name: Run Jest tests
        run: yarn test
